language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

# commands to install with dependencies
install:
  - "pip install --upgrade pip"
  - "pip install --upgrade pytest"
  - "pip install --upgrade --force-reinstall setuptools"
  - "pip install gunicorn"
  - "pip install huckle"
  - "pip install -e ."

# command to run tests
script: python -m pytest
